### ISSUE TITLE
Element SESSIONMANAGEMENT is undefined in a Java object of type class coldfusion.runtime.StructBean

### ISSUE THREAD

**Issue by kkorry** [TheRealAgentK/facebook-cf-sdk#39] opened 2012-04-21 04:21 UTC
Element SESSIONMANAGEMENT is undefined in a Java object of type class coldfusion.runtime.StructBean

What does this mean?

**Comment by benorama** [comment] 2012-05-05 09:20
When do you get this error?
Could you give us more details?
Thanks.

**Comment by benorama** [comment] 2012-05-14 14:15
I close this issue since no more details have been given to reproduce the issue.

**Closed as completed by benorama** 2012-05-14 14:15 UTC

**Comment by qualifio-zz** [comment] 2012-05-29 09:51
Hi,

I've the same problem.

I installed CF10 on a Debian server.

This problem occures in: 

Expression Exception - in /mnt/web/09janrain/fbsdk/FacebookBase.cfc : line 232
Element SESSIONMANAGEMENT is undefined in a Java object of type class coldfusion.runtime.StructBean.

Which informations could I give to help you?

thanks,

Christophe

**Comment by qualifio-zz** [comment] 2012-05-29 10:17
Hi,

You can see this error here: http://178.33.197.209:1080/fbtest/examples/website/

Thanks for your help,

Christophe

**Comment by benorama** [comment] 2012-05-29 10:25
We do not have CF10 installed here.
It looks like there is some changes...

Can you try to dump application.getApplicationSettings() to see if there is 'sessionManagement' in the struct?

If it doesn't, as a workaround, you can change 
`return application.getApplicationSettings().sessionManagement;`
by
`return true;`
Since session management is enabled most of the time...

**Comment by qualifio-zz** [comment] 2012-05-29 13:42
Hi

Here's the cfdump :

object of coldfusion.runtime.ApplicationSettings
Class Name  coldfusion.runtime.ApplicationSettings
Methods  
Method  Return Type
getAuthCookieTimeout()  int
getInMemorySize()   int
getSessionCookieDomain()    java.lang.String
getSessionCookieTimeout()   int
isAuthCookieUpdateDisabled()    boolean
isHttpOnlySessionCookie()   boolean
isInMemoryEnabled()     boolean
isInvokeAccessorEnabled()   boolean
isSecureSessionCookie()     boolean
isSessionCookieUpdateDisabled()     boolean
Fields  
Field   Value
java.lang.String AUTH_COOKIE    AUTHCOOKIE
java.lang.String DISABLEUPDATE  DISABLEUPDATE
java.lang.String DOMAIN     DOMAIN
java.lang.String HTTPONLY   HTTPONLY
java.lang.String INMEMORY_FILESYSTEM    inmemoryfilesystem
java.lang.String INMEMORY_FILESYSTEM_ENABLED    enabled
java.lang.String INMEMORY_FILESYSTEM_SIZE   size
java.lang.String INVOKE_ACCESSOR    invokeimplicitaccessor
java.lang.String SECURE     SECURE
java.lang.String SESSION_COOKIE     SESSIONCOOKIE
java.lang.String TIMEOUT    TIMEOUT 

Thanks for your help, it works with "return true"!

Christophe

**Comment by benorama** [comment] 2012-06-06 06:56
I've pushed a fix that always return true for isPersistentEnabled().

**Comment by qualifio-zz** [comment] 2012-06-06 07:43
Thank you very much for your help !!!
